package com.mycompany.myapp;


import static com.codename1.ui.CN.*;
import com.codename1.ui.Display;
import com.codename1.ui.Form;
import com.codename1.ui.Dialog;
import com.codename1.ui.Label;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import com.codename1.io.Log;
import com.codename1.ui.Toolbar;
import java.io.IOException;
import com.codename1.ui.layouts.BoxLayout;
import com.codename1.io.NetworkEvent;
import views.ChatBot;
import views.Corona;
import views.ListerPharmacie;
import views.Recherche;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose 
 * of building native mobile applications using Java.
 */
public class MyApplication {

    private Form current;
    private Resources theme;

    public void init(Object context) {
        // use two network threads instead of one
        updateNetworkThreadCount(2);

        theme = UIManager.initFirstTheme("/theme");

        // Enable Toolbar on all Forms by default
        Toolbar.setGlobalToolbar(true);

        // Pro only feature
        Log.bindCrashProtection(true);

        addNetworkErrorListener(err -> {
            // prevent the event from propagating
            err.consume();
            if(err.getError() != null) {
                Log.e(err.getError());
            }
            Log.sendLogAsync();
            Dialog.show("Connection Error", "There was a networking error in the connection to " + err.getConnectionRequest().getUrl(), "OK", null);
        });        
    }
    
    public void start() {
        if(current != null){
            current.show();
            return;
        }
      //   Form hi = new Form("Projet", BoxLayout.y());
       // hi.add(new Recherche(hi));
           //Form hi = new Form("Projet", BoxLayout.y());
       // hi.add(new ListerPharmacie(hi));
       Form hi= new Corona();
        hi.show();
          /* String ch = text.getText();
           String  ch2=ch.replace(" ","%20");
            System.out.println(ch2);
            HttpResponse<String> response = Unirest.get("https://acobot-brainshop-ai-v1.p.rapidapi.com/get?bid=155900&key=CZainXOvM6BlGVtY&uid=pidev&msg="+ch2)
                    .header("x-rapidapi-key", "acd422d7b6msh682a6b9121a4397p1f6684jsnfd86ac745d6b")
                    .header("x-rapidapi-host", "acobot-brainshop-ai-v1.p.rapidapi.com")
                    .asString();
            System.out.println(response.getBody());*/
    }

    public void stop() {
        current = getCurrentForm();
        if(current instanceof Dialog) {
            ((Dialog)current).dispose();
            current = getCurrentForm();
        }
      
    }
    
    public void destroy() {
    }

}
